# Generated by Django 5.2.1 on 2025-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_title'], name='content_man_course__8d52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_description'], name='content_man_course__962575_idx'),
        ),
    ]
