# Generated by Django 5.2.1 on 2025-05-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_system.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_system.coursetype'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_system.courselesson'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_system.topictype'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_title'], name='content_man_course__8d52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_description'], name='content_man_course__962575_idx'),
        ),
    ]
