# Generated by Django 5.2.1 on 2025-05-30 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='content_management_system.authordetails'),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='authored_courses', through='content_management_system.AuthorDetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authordetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='content_management_system.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content_management_system.coursecategory'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content_management_system.course'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content_management_system.coursecomment'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content_management_system.course'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content_management_system.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content_management_system.coursetype'),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content_management_system.courselesson'),
        ),
        migrations.AddField(
            model_name='topictype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_topic_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='content_management_system.topictype'),
        ),
        migrations.AlterUniqueTogether(
            name='authordetails',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courselesson',
            unique_together={('course', 'lesson_slug')},
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_title'], name='content_man_course__8d52f7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_description'], name='content_man_course__962575_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='content_man_is_publ_a267d0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='content_man_is_acti_339795_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together={('lesson', 'topic_slug')},
        ),
    ]
