# Generated by Django 5.2.1 on 2025-05-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0002_course_content_man_course__8d52f7_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='description',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='slug',
            new_name='course_slug',
        ),
    ]
