# Generated by Django 5.2.1 on 2025-05-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0003_course_course_banner_course_course_views_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='authored_courses', through='content_management_system.AuthorDetails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management_system.course'),
        ),
        migrations.AlterUniqueTogether(
            name='authordetails',
            unique_together={('course', 'user')},
        ),
    ]
