# Generated by Django 5.2.1 on 2025-05-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0005_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
