# Generated by Django 5.2.1 on 2025-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0006_alter_course_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictype',
            name='topic_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
