# Generated by Django 5.2.1 on 2025-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0007_alter_topictype_topic_slug_alter_topictype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictype',
            name='topic_slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='type_name',
            field=models.CharField(max_length=200),
        ),
    ]
