# Generated by Django 5.2.1 on 2025-05-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0008_alter_topictype_topic_slug_alter_topictype_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authordetails',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='authordetails',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authordetails',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='content_management_system.course'),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='bio',
        ),
    ]
