# Generated by Django 5.2.1 on 2025-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management_system', '0011_authordetails_consent_date_authordetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
